### ISSUE TITLE
[Linux] - Build failure with gcc 12 - exchange not member of std

### ISSUE THREAD

**Issue by ycollet** [BambooTracker/BambooTracker#445]
I try to compile BambooTracker on Fedora 36 with gcc 12.
BambooTracker fails to build. Certainly a missing #include <utility>:
```
g++ -c -fPIC -I. -Iinstrument -Imodule -I../submodules/emu2149/src -I../submodules/RtAudio/src -I../submodules/RtMidi/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o song_length_calculator.o song_length_calculator.cpp
song_length_calculator.cpp: In member function 'void SongLengthCalculator::totalStepCount(size_t&, size_t&) const':
song_length_calculator.cpp:176:38: error: 'exchange' is not a member of 'std'
  176 |                 const int odr = std::exchange(curOrder, (curOrder + 1) % (lastOrder + 1));
      |                                      ^~~~~~~~
```

**Comment by OPNA2608** [comment]
Thanks for the report. I'll install Fedora on a spare system and check if that's the only problem with GCC12.

**Comment by ycollet** [comment]
Thanks a lot !

**Comment by OPNA2608** [comment]
I've fixed the missing header in https://github.com/BambooTracker/BambooTracker/commit/7d7ba47dea4782f1b13c95b9648e4b1865cf68af. That should be the only build problem you'll encounter on Fedora 36 with GCC12, as long as `CONFIG+=system_rtaudio` isn't used (because Fedora's RtAudio package is too outdated - 5.0.0).

However, the binary will trigger a segfault in Fedora's pipewire if the vendored RtAudio 5.2.0 is built with JACK support:

```
Thread 10 "pw-RtApiJackCou" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbf7fe640 (LWP 30378)]
client_node_transport (object=0x3ecc180, readfd=35, writefd=34, mem_id=0, offset=0, size=2312) at ../pipewire-jack/src/pipewire-jack.c:1536
1536		c->socket_source = pw_loop_add_io(c->loop->loop,
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-core-2.42.0-2.fc36.x86_64 atk-2.36.0-5.fc36.x86_64 cairo-1.17.4-7.fc36.x86_64 cairo-gobject-1.17.4-7.fc36.x86_64 dbus-libs-1.13.20-3.fc36.x86_64 dconf-0.40.0-6.fc36.x86_64 expat-2.4.6-1.fc36.x86_64 flac-libs-1.3.3-10.fc36.x86_64 fontconfig-2.13.96-1.fc36.x86_64 gdk-pixbuf2-2.42.6-3.fc36.x86_64 glibc-2.35-2.fc36.x86_64 gvfs-client-1.49.90-1.fc36.x86_64 harfbuzz-3.3.2-1.fc36.x86_64 libXau-1.0.9-8.fc36.x86_64 libXrandr-1.5.2-8.fc36.x86_64 libdrm-2.4.109-2.fc36.x86_64 libepoxy-1.5.9-2.fc36.x86_64 libselinux-3.3-4.fc36.x86_64 libstemmer-0-18.585svn.fc36.x86_64 libthai-0.1.29-2.fc36.x86_64 libtracker-sparql-3.3.0~rc-1.fc36.x86_64 libwayland-client-1.20.0-3.fc36.x86_64 libwayland-cursor-1.20.0-3.fc36.x86_64 libwayland-egl-1.20.0-3.fc36.x86_64 libwayland-server-1.20.0-3.fc36.x86_64 libxcb-1.13.1-9.fc36.x86_64 libxshmfence-1.3-10.fc36.x86_64 mesa-dri-drivers-21.3.6-1.fc36.x86_64 mesa-libEGL-22.0.1-1.fc36.x86_64 ncurses-libs-6.2-9.20210508.fc36.x86_64 pango-1.50.5-1.fc36.x86_64 pcre-8.45-1.fc36.1.x86_64 pipewire-libs-0.3.47-1.fc36.x86_64 qgnomeplatform-qt6-0.8.4-6.fc36.x86_64 qt6-qtwayland-6.2.3-2.fc36.x86_64 sqlite-libs-3.36.0-5.fc36.x86_64 vulkan-loader-1.3.204.0-1.fc36.x86_64 xz-libs-5.2.5-8.fc36.x86_64
(gdb) bt
#0  client_node_transport (object=0x3ecc180, readfd=35, writefd=34, mem_id=0, offset=0, size=2312) at ../pipewire-jack/src/pipewire-jack.c:1536
#1  0x00007fffe00a1774 in client_node_demarshal_transport.lto_priv () at /usr/lib64/pipewire-0.3/libpipewire-module-client-node.so
#2  0x00007fffe00db964 in process_remote () at /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#3  0x00007fffe00dbfb8 in on_remote_data () at /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#4  0x00007fffe5922df5 in loop_iterate () at /usr/lib64/spa-0.2/support/libspa-support.so
#5  0x00007ffff5ff3a72 in do_loop () at /lib64/libpipewire-0.3.so.0
#6  0x00007ffff61b80b7 in start_thread () at /lib64/libc.so.6
#7  0x00007ffff623d800 in clone3 () at /lib64/libc.so.6
```

There was a patch in RtAudio to fix some JACK API problems that showed up with pipewire on Fedora 3**5** (https://github.com/thestk/rtaudio/commit/b7ff1039d0c7fe526acceb5c18a6111a63753dbf), but it doesn't seem to help with this particular segfault. I haven't looked too deeply into whose fault this is (pipewire not handling something well? RtAudio incorrectly communicating with its JACK interface? BambooTracker doing something wrong somewhere?).

As a workaround, build BambooTracker with CMake instead of QMake and pass `-DRTAUDIO_API_JACK=OFF` to disable RtAudio's JACK support. If you want to stick with QMake (which has no way of conveniently disabling this support rn), you'll have to comment out [this block](https://github.com/BambooTracker/BambooTracker/blob/7d7ba47dea4782f1b13c95b9648e4b1865cf68af/submodules/RtAudio/RtAudio.pro#L64-L76).

**Comment by ycollet** [comment]
Thanks for these informations. I will add this to my spec file.
