### ISSUE TITLE
[All] - Crash when importing malformed BTB bank

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#447]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Importing the attached bank causes a segfault.

<details>
  <summary>GDB Backtrace</summary>

```console
Thread 1 ".BambooTracker-" received signal SIGSEGV, Segmentation fault.
io::BinaryContainer::readString[abi:cxx11](unsigned long, unsigned long) const (this=this@entry=0x7fffffff8ff0, offset=offset@entry=737, length=<optimized out>) at io/binary_container.cpp:234
warning: Source file is more recent than executable.
234		return std::string(buf_.begin() + static_cast<int>(offset), buf_.begin() + static_cast<int>(offset + length));
(gdb) bt
#0  io::BinaryContainer::readString[abi:cxx11](unsigned long, unsigned long) const (this=this@entry=0x7fffffff8ff0, offset=offset@entry=737, length=<optimized out>) at io/binary_container.cpp:234
#1  0x00000000004aa76e in io::BtbIO::load (this=<optimized out>, ctr=...) at io/btb_io.cpp:89
#2  0x000000000064ebe3 in io::BankIO::loadBank (this=this@entry=0x3e46a10, ctr=..., path="/dev/shm/snow_angels.btb") at io/bank_io.cpp:87
#3  0x00000000004f6055 in MainWindow::funcImportInstrumentsFromBank (this=0x7fffffffaeb0, file=...) at gui/mainwindow.cpp:1845
#4  0x00000000004f7c1c in MainWindow::importInstrumentsFromBank (this=0x7fffffffaeb0) at gui/mainwindow.cpp:1824
#5  0x0000000000659321 in MainWindow::qt_static_metacall (_a=0x7fffffff9320, _id=60, _c=QMetaObject::InvokeMetaMethod, _o=0x7fffffffaeb0) at moc_mainwindow.cpp:574
#6  MainWindow::qt_metacall (this=0x7fffffffaeb0, _c=QMetaObject::InvokeMetaMethod, _id=60, _a=0x7fffffff9320) at moc_mainwindow.cpp:725
#7  0x00007ffff6fa8410 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#8  0x00007ffff7a31e42 in QAction::triggered(bool) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#9  0x00007ffff7a34a88 in QAction::activate(QAction::ActionEvent) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#10 0x00007ffff7bbbf82 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#11 0x00007ffff7bc3c11 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#12 0x00007ffff7a7a98e in QWidget::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#13 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#14 0x00007ffff7a3fd1b in QApplication::notify(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#15 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#16 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#17 0x00007ffff7a3ed47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#18 0x00007ffff7a949ae in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#19 0x00007ffff7a97125 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#20 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#21 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#22 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#23 0x00007ffff7381bd3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#24 0x00007ffff73575cc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#25 0x00007fffe5e6ac4a in ?? () from /nix/store/7ga5dkcih344b0qfpf36zv2gmcn925qr-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5XcbQpa.so.5
#26 0x00007ffff40a9e3b in g_main_context_dispatch () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#27 0x00007ffff40aa0e8 in g_main_context_iterate.constprop () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#28 0x00007ffff40aa19f in g_main_context_iteration () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#29 0x00007ffff6fc96c0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#30 0x00007ffff6f7003b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#31 0x00007ffff7bc15f4 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#32 0x00007ffff7bc171f in QMenu::exec(QPoint const&, QAction*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#33 0x00000000004f912d in MainWindow::on_instrumentList_customContextMenuRequested (this=0x7fffffffaeb0, pos=...) at gui/mainwindow.cpp:2571
#34 0x0000000000659321 in MainWindow::qt_static_metacall (_a=0x7fffffffa270, _id=2, _c=QMetaObject::InvokeMetaMethod, _o=0x7fffffffaeb0) at moc_mainwindow.cpp:574
#35 MainWindow::qt_metacall (this=0x7fffffffaeb0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffa270) at moc_mainwindow.cpp:725
#36 0x00007ffff6fa8410 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#37 0x00007ffff7a5fc25 in QWidget::customContextMenuRequested(QPoint const&) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#38 0x00007ffff7a7b7f0 in QWidget::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#39 0x00007ffff7b27f8e in QFrame::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#40 0x00007ffff6f71403 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#41 0x00007ffff7a3875e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#42 0x00007ffff7a409c1 in QApplication::notify(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#43 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#44 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#45 0x00007ffff7a94604 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#46 0x00007ffff7a97125 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#47 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#48 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#49 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#50 0x00007ffff7381bd3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#51 0x00007ffff73575cc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#52 0x00007fffe5e6ac4a in ?? () from /nix/store/7ga5dkcih344b0qfpf36zv2gmcn925qr-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5XcbQpa.so.5
#53 0x00007ffff40a9e3b in g_main_context_dispatch () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#54 0x00007ffff40aa0e8 in g_main_context_iterate.constprop () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#55 0x00007ffff40aa19f in g_main_context_iteration () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#56 0x00007ffff6fc96c0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#57 0x00007ffff6f7003b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#58 0x00007ffff6f78620 in QCoreApplication::exec() () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#59 0x0000000000454d16 in main (argc=<optimized out>, argv=0x7fffffffb2f8) at main.cpp:69
```

Sometimes slightly different:

```console
Thread 1 ".BambooTracker-" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*> > (__k2=..., __k1=..., __p=0x7ffe36afb32f "") at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:379
379		   traits_type::assign(*__p, *__k1); // These types are off.
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*> > (__k2=..., __k1=..., __p=0x7ffe36afb32f "")
    at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:379
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*> > (__end=..., __beg=..., this=0x7fffffff8dd0)
    at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.tcc:225
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*> > (__end=..., __beg=..., this=0x7fffffff8dd0)
    at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:247
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*> > (__end=..., __beg=..., this=0x7fffffff8dd0)
    at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:266
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::_Deque_iterator<unsigned char, unsigned char const&, unsigned char const*>, void> (__a=..., __end=..., __beg=..., this=0x7fffffff8dd0)
    at /nix/store/2dll4xl0xn13anzfxk0pbjr209s6rwhx-gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:628
#5  io::BinaryContainer::readString[abi:cxx11](unsigned long, unsigned long) const (this=this@entry=0x7fffffff8ff0, offset=offset@entry=737, length=<optimized out>) at io/binary_container.cpp:234
#6  0x00000000004aa76e in io::BtbIO::load (this=<optimized out>, ctr=...) at io/btb_io.cpp:89
#7  0x000000000064ebe3 in io::BankIO::loadBank (this=this@entry=0x47a6a50, ctr=..., path="/dev/shm/snow_angels.btb") at io/bank_io.cpp:87
#8  0x00000000004f6055 in MainWindow::funcImportInstrumentsFromBank (this=0x7fffffffaeb0, file=...) at gui/mainwindow.cpp:1845
#9  0x00000000004f7c1c in MainWindow::importInstrumentsFromBank (this=0x7fffffffaeb0) at gui/mainwindow.cpp:1824
#10 0x0000000000659321 in MainWindow::qt_static_metacall (_a=0x7fffffff9320, _id=60, _c=QMetaObject::InvokeMetaMethod, _o=0x7fffffffaeb0) at moc_mainwindow.cpp:574
#11 MainWindow::qt_metacall (this=0x7fffffffaeb0, _c=QMetaObject::InvokeMetaMethod, _id=60, _a=0x7fffffff9320) at moc_mainwindow.cpp:725
#12 0x00007ffff6fa8410 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#13 0x00007ffff7a31e42 in QAction::triggered(bool) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#14 0x00007ffff7a34a88 in QAction::activate(QAction::ActionEvent) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#15 0x00007ffff7bbbf82 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#16 0x00007ffff7bc3c11 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#17 0x00007ffff7a7a98e in QWidget::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#18 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#19 0x00007ffff7a3fd1b in QApplication::notify(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#20 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#21 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#22 0x00007ffff7a3ed47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#23 0x00007ffff7a949ae in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#24 0x00007ffff7a97125 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#25 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#26 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#27 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#28 0x00007ffff7381bd3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#29 0x00007ffff73575cc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#30 0x00007fffe5e6ac4a in ?? () from /nix/store/7ga5dkcih344b0qfpf36zv2gmcn925qr-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5XcbQpa.so.5
#31 0x00007ffff40a9e3b in g_main_context_dispatch () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#32 0x00007ffff40aa0e8 in g_main_context_iterate.constprop () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#33 0x00007ffff40aa19f in g_main_context_iteration () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#34 0x00007ffff6fc96c0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#35 0x00007ffff6f7003b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#36 0x00007ffff7bc15f4 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#37 0x00007ffff7bc171f in QMenu::exec(QPoint const&, QAction*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#38 0x00000000004f912d in MainWindow::on_instrumentList_customContextMenuRequested (this=0x7fffffffaeb0, pos=...) at gui/mainwindow.cpp:2571
#39 0x0000000000659321 in MainWindow::qt_static_metacall (_a=0x7fffffffa270, _id=2, _c=QMetaObject::InvokeMetaMethod, _o=0x7fffffffaeb0) at moc_mainwindow.cpp:574
#40 MainWindow::qt_metacall (this=0x7fffffffaeb0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffa270) at moc_mainwindow.cpp:725
#41 0x00007ffff6fa8410 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#42 0x00007ffff7a5fc25 in QWidget::customContextMenuRequested(QPoint const&) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#43 0x00007ffff7a7b7f0 in QWidget::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#44 0x00007ffff7b27f8e in QFrame::event(QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#45 0x00007ffff6f71403 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#46 0x00007ffff7a3875e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#47 0x00007ffff7a409c1 in QApplication::notify(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#48 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#49 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#50 0x00007ffff7a94604 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#51 0x00007ffff7a97125 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#52 0x00007ffff7a3876f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Widgets.so.5
#53 0x0000000000656753 in QApplicationWrapper::notify (this=<optimized out>, receiver=<optimized out>, event=<optimized out>) at gui/q_application_wrapper.cpp:35
#54 0x00007ffff6f7169a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#55 0x00007ffff7381bd3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#56 0x00007ffff73575cc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Gui.so.5
#57 0x00007fffe5e6ac4a in ?? () from /nix/store/7ga5dkcih344b0qfpf36zv2gmcn925qr-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5XcbQpa.so.5
#58 0x00007ffff40a9e3b in g_main_context_dispatch () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#59 0x00007ffff40aa0e8 in g_main_context_iterate.constprop () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#60 0x00007ffff40aa19f in g_main_context_iteration () from /nix/store/3ma88r781fvsjiakwyfh95mzy7k19jac-glib-2.72.0/lib/libglib-2.0.so.0
#61 0x00007ffff6fc96c0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#62 0x00007ffff6f7003b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#63 0x00007ffff6f78620 in QCoreApplication::exec() () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#64 0x0000000000454d16 in main (argc=<optimized out>, argv=0x7fffffffb2f8) at main.cpp:69
```

</details>

## How to reproduce

1. Import From Bank File…
2. Load [snow_angels.btb](https://github.com/BambooTracker/BambooTracker/files/8543618/snow_angels.btb.zip)
3. Crash

## System Information

- **Operating System**: All
- **BambooTracker Version**: unstable 7d7ba47dea4782f1b13c95b9648e4b1865cf68af
- **Build Type**: Official & Locally

**Comment by OPNA2608** [comment]
Bank seems broken: Instrument count is set to 10 but there are only 11 entries. It tries to read the elusive 11th entry's name from data that isn't instrument metadata & crashes on that.

Not sure how it happened, nor if the bug that caused it still exists (very old bank). Closing, but can reopen if there is a way to reproduce this broken file saving on the current version. I sent a corrected version to the affected person.

**Comment by OPNA2608** [comment]
Actually gonna reopen this, the bank itself is broken but it should handle such an error without crashing.

**Comment by rerrahkr** [comment]
Thank you for your report and request. I added binary container read/write range check at b38b6b0eb08d3e845e60cf0a98717a73215e0559 to avoid segmentation fault.

**Comment by OPNA2608** [comment]
![Bildschirmfoto von 2022-05-29 11-35-40](https://user-images.githubusercontent.com/23431373/170861591-100ed6be-b5c2-4d25-9b56-74430315a1be.png)

Thanks!
